### ISSUE TITLE
Support for Joins

### ISSUE THREAD

**Issue by pjebs** [mithrandie/csvq-driver#1]
Can we support INNER JOINS similar to https://github.com/dinedal/textql?

**Comment by mithrandie** [comment]
@pjebs 

JOIN syntax is supported. The syntax is described in the following URL page.

[https://mithrandie.github.io/csvq/reference/select-query.html#from_clause](https://mithrandie.github.io/csvq/reference/select-query.html#from_clause)

If it does not work, it is a bug, so please issue again.
