### ISSUE TITLE
Quote characters

### ISSUE THREAD

**Issue by 89z** [mithrandie/csvq-driver#3]
SQLite support these:

~~~
'keyword'
"keyword"
[keyword]
`keyword`
~~~

https://www.sqlite.org/lang_keywords.html

It seems CSVQ only support this:

~~~
`keyword`
~~~

Example:

~~~
CREATE TABLE `artist_t.csv`(artist_n, artist_s)
~~~

this makes it impossible to have long query, can you cant do something like this:

~~~
CREATE
TABLE
`artist_t.csv`
(artist_n, artist_s)
~~~

as you cant put backtick inside another backtick

**Comment by 89z** [comment]
Ugly workaround:

~~~
fmt.Sprint(
   "CREATE",
   "TABLE",
   "`artist_t.csv`",
   "(artist_n, artist_s)",
)
~~~

**Comment by 89z** [comment]
I figured it out. You have to set ANSI_QUOTES, and you have to do it as a
separate command:

~~~go
db.Exec("SET @@ANSI_QUOTES TO TRUE")
db.Exec(`CREATE TABLE "artist_t.csv" (artist_n, artist_s)`)
~~~

**Comment by mithrandie** [comment]
In version 1.3.0, some parameters are now supported to be specified in a DSN string.

By opening a connection as below, you can specify ANSI_QUOTES without having to run a separate command.
```go
db, err := sql.Open("csvq", "/path/to/data/directory?AnsiQuotes=true")
```

Thank you.
