### ISSUE TITLE
Config the CSV delimiter

### ISSUE THREAD

**Issue by mazux** [mithrandie/csvq-driver#9]
I'm unable to parse a `;` delimiter csv files

Any idea how to do so? 
I was thinking of creating a PR in which I add another param to the connection string to specify the CSV delimiter

**Comment by mithrandie** [comment]
Can you try this statement?

```
db.QueryRowContext(ctx, "SET @@DELIMITER TO ';'; SELECT * FROM `foo.csv`")
```

cf. https://mithrandie.github.io/csvq/reference/flag.html
